### ISSUE TITLE
Refactorizar las pruebas de integración

### ISSUE THREAD

**Issue by wingkei1** [wingkei1/WebsitesMonitorization#44]
Tiempo estimado: 2h
Tiempo real:

**Comment by ignacio-upm** [comment]
He tenido que hacer el push directamente desde master por problemas en el merge de la rama. Por eso no he podido lincearlo al PR correspondiente.

Intento corregir dependencias de Spring boot: 1h 20 min
Terminar por refactorizar el código como solución: 40 min
Terminar los test: 1 h
